name: Nightly builds
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'

jobs:
    nightly_build_on_linux:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: '22.x'
            - name: update package directory
              run: sudo apt update
            - name: install rpm and libarchive
              run: sudo apt install rpm libarchive-tools
            - name: install dependencies
              run: npm install
            - name: run unit tests
              run: npm run test
            - name: build
              run: npm run electron:linux
            - name: fetch current version
              id: ver_name
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: 'package.json'
                  prop_path: 'version'
            - name: uploading rpm artifact
              uses: actions/upload-artifact@v4
              with:
                  name: dopamine-nightly-rpm
                  path: release/Dopamine-*.rpm
            - name: upload deb artifact
              uses: actions/upload-artifact@v4
              with:
                  name: dopamine-nightly-deb
                  path: release/Dopamine-*.deb
            - name: upload appimage artifact
              uses: actions/upload-artifact@v4
              with:
                  name: dopamine-nightly-appimage
                  path: release/Dopamine-*.AppImage
            - name: upload snap artifact
              uses: actions/upload-artifact@v4
              with:
                  name: dopamine-nightly-snap
                  path: release/Dopamine-*.snap
            - name: upload pacman artifact
              uses: actions/upload-artifact@v4
              with:
                  name: dopamine-nightly-pacman
                  path: release/Dopamine-*.pacman

    nightly_build_on_mac_arm:
        runs-on: macos-15
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: '22.x'
            - name: install dependencies
              run: npm install
            - name: run unit tests
              run: npm run test
            - name: build
              run: npm run electron:mac
            - name: fetch current version
              id: ver_name
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: 'package.json'
                  prop_path: 'version'
            - name: upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dopamine-nightly-macos-arm
                  path: release/Dopamine-*.dmg

    nightly_build_on_mac_intel:
        runs-on: macos-15-intel
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: '22.x'
            - name: install dependencies
              run: npm install
            - name: run unit tests
              run: npm run test
            - name: build
              run: npm run electron:mac
            - name: fetch current version
              id: ver_name
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: 'package.json'
                  prop_path: 'version'
            - name: upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dopamine-nightly-macos-intel
                  path: release/Dopamine-*.dmg

    nightly_build_on_win:
        runs-on: windows-2022
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: '22.x'
            - name: Install dependencies
              run: npm install
            - name: Run unit tests
              run: npm run test
            - name: Build
              run: npm run electron:windows
            - name: Fetch current version
              id: ver_name
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: 'package.json'
                  prop_path: 'version'
            - name: Download and Install 7-Zip
              run: |
                  curl -L -o 7z.exe https://www.7-zip.org/a/7z2201-x64.exe
                  Start-Process -FilePath 7z.exe -ArgumentList '/S' -Wait
            - name: Create 7z Archive With Only EXE Files
              shell: cmd
              run: |
                  cd release
                  "C:\Program Files\7-Zip\7z.exe" a ../dopamine-nightly-win.7z Dopamine-*.exe
            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: dopamine-nightly-win
                  path: dopamine-nightly-win.7z
